Branch a
Tofcookies/First-project pull request #1
Opened 2021-08-11 19:33 UTC by Tofcookies

https://github.com/Tofcookies/First-project/pull/new/branch-A

2021-08-11 19:37 UTC, Tofcookies commented
https://github.com/Tofcookies/First-project.git

2021-08-11 19:54 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @Tofcookies , You did a great job so far 👏🏼 👏🏼 

- The commit messages are descriptive. Good job!

However, here are some points that you need to work on to get your project approved.

## Required changes :

- [ ] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-11 19:54 UTC, safafa commented on test.md
> +This file should be ignored by git
- [ ] this file should be ignored by git as required. Kindly fix the issue so that you can get your project approved. 
- [ ] I think adding node_modules to .gitignore is a good practice since it can be added by accident while setting up linters.
- [ ] Kindly add the [linters](https://github.com/microverseinc/linters-config/tree/master/html-css) configuration to your project. I think using linters is good practice as it will help you create clean code.
- [ ] For your project to look professional I think having a descreptive readme is a must. Kindly modify your readme file you can use [this template](https://github.com/microverseinc/readme-template). Modify the sections according to the project and you can delete the unused sections.
- [ ] Again for the same reason having a descriptive pull request title and comment is also good. Kindly edit them. You can create a small summary of the changes in the comment.

2021-08-12 09:54 UTC, Tofcookies commented on test.md
> +This file should be ignored by git
Thank you for the observation

2021-08-12 10:38 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @Tofcookies 

Great work on implementing the changes requested by the previous reviewer, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
 
  Changes required:

          Use past tense while you making the descriptive PR.
          Work on the all changes requested by the previous reviewer
          Please refer to the Microverse template to setup the linters
         * #### Please check the comments under the review too
     
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-12 10:38 UTC, Emmyn5600 commented on test.md
> +This file should be ignored by git
Please correct all changes requested by the previous code reviewer before you request for re-review.

2021-08-13 14:09 UTC, Emmyn5600 approved these changes
## STATUS: APPROVED :muscle::clap:

Hi, @Tofcookies 

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous code reviewers. Kudos
   
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-16 10:42 UTC, george-shammar commented
@Tofcookies , This project has already been approved by @Emmyn5600. I tried to reach you on slack to enquire if there's any particular reason for re-submitting a CRR but I couldn't find you on slack. Hence, I'll have to invalidate the CRR. Cheers and regards.

2021-08-17 07:38 UTC, merged